"""
URL configuration for college_chatbot project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/urls/
For the full list of URLS, see
https://docs.djangoproject.com/en/5.2/ref/urls/
"""
from django.contrib import admin
from django.urls import path, include
from chat_api import views as chat_views # <-- 1. This imports your views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('chat_api.urls')),  # <-- This is your API path
    
    # 2. This is the new line that fixes your 404 error
    # It tells Django to load your 'chat_page' function
    # when someone visits the homepage (the empty path '')
    path('', chat_views.chat_page, name='chat_page'), 
]

